services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_prod
    command: npm run build
    ports:
      - "80:3000"
    env_file:
      - .env.prod

  db:
    image: postgres:16
    container_name: postgres_prod
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

volumes:
  db_data:
